'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Placement_System.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1456496322_30754_Apple_Google_Facebook_And_Microsoft_Unite_For_iPhone_Encryption_Fight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1456496322-30754-Apple-Google-Facebook-And-Microsoft-Unite-For-iPhone-Encryption-"& _ 
                        "Fight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Abstract_digital_information_Wallpaper_HD_2560x1440() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Abstract digital information Wallpaper HD 2560x1440", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property air_bubble_world_creative_wallpaper_1366x768() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("air-bubble-world-creative-wallpaper-1366x768", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property air_bubble_world_creative_wallpaper_1366x7681() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("air-bubble-world-creative-wallpaper-1366x7681", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property air_bubble_world_creative_wallpaper_1366x7682() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("air-bubble-world-creative-wallpaper-1366x7682", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property application_development() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application-development", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property application_development1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application-development1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property banner_img03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner-img03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blue_blue_sky_by_youwatchmebleedg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue_blue_sky_by_youwatchmebleedg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cloud_communications() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cloud-communications", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EIM_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EIM-3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iStock_000038236708_Medium1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iStock_000038236708_Medium1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iStock_000038236708_Medium11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iStock_000038236708_Medium11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property job_sec_header() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("job_sec_header", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property job_sec_header1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("job_sec_header1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property me8371237_blue_global_business_interface_ireland_hd_a0072() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("me8371237-blue-global-business-interface-ireland-hd-a0072", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property most_valuable_companies_apple_google_ibm_microsoft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("most-valuable-companies-apple-google-ibm-microsoft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mysuite_servicios_integracion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mysuite-servicios-integracion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property new5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property notebook_server_keyboard_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notebook-server-keyboard-white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property placement02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("placement02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portal_promo_art() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portal-promo-art", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property recruitment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("recruitment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property risky_dream_career() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("risky-dream-career", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
